config/routes.rb
Rails.application.routes.draw do
  resources:projects do
		resources :tasks,only:[:create,:destroy]
	end
	post 'projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

	root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	validates :title,presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	validates :title,presence:true
	validates :project_id,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :set_project, only:[:show,:edit,:update,:destroy]	

	def index
		@projects = Project.all
	end

	def show
	end

	def new
		@project = Project.new
	end

	def edit
	end

	def create
		@project = Project.new(project_params)
		respond_to do |format|
			if @project.save
				format.html{ redirect_to @project, notice: 'Project was successfully created.' }
				format.json{ render :show,status: :created,location: @project }
			else
				format.html{ render :new}
				format.json{ render json: @project.errors, status: :unprocessable_entity }
			end
		end
	end
	
	def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
	
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	private
  def project_params
    params.require(:project).permit(:title, :content)
  end

	def set_project
		@project = Project.find(params[:id])
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		@task = @project.tasks.create(task_params)
	
		respond_to do |format|	
			if @project.save
				format.html{ redirect_to project_path(@project.id), notice:'Project was successfully created.'}
				format.json{ rnder :show,status: :created, location:@project}
			else
				format.html{ redirect_to project_path(@project.id) }
				format.json{ render json:@project.errors,status: :unprocessabie_entry}
			end
		end
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to project_path(params[:project_id])
	end

	def toggle
		render nothing:true
		@task = Task.find(params[:id])
		@task.done = !@task.done
		@task.save
	end

	private
	def task_params
		params.require(:task).permit(:title)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.content %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<ul>
  <% @project.tasks.each do |task| %>
    <li>
		<%= check_box_tag '','',task.done,{ 'data-id' => task.id,'data-project_id'=>task.project_id}%>
		<%=task.title%>
		<%= link_to"[Delete]",project_task_path(task.project_id,task.id),method: :delete,data:{confirm:'Are you sure?'}%>
		</li>

  <% end %>
</ul>
<li>
  <%= form_for [@project, @project.tasks.build] do |f| %>
    <%= f.text_field :title %>
    <%= f.submit %>
  <% end %>
</li>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<script>
$(function(){
	$("input[type=checkbox]").click(function() {
		$.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle');
	});
});
</script>